### ISSUE TITLE
Tracking: Deployment of Miraheze

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/puppet#1]
The first issue and the biggest one. A tracking list of all things that need to be done before Miraheze can be considered public perse. Can be done in any order but all must be done before 'Deployment' can be started.

- [x] Services
 - [x] Ganglia! @JohnFLewis
 - [x] Fix Icinga @JohnFLewis
 - [x] Enable "zones_strict_data" for GDNSD @JohnFLewis
- [x] Cleanup
 - [x] Clean MediaWiki databases and start again @Southparkfan 
 - [x] Puppetise puppet-run runs @JohnFLewis
- [x] MediaWiki
 - [x] Fix CentralAuth login issues @Southparkfan @Reception123
 - [x] Write CreateWiki extension @Southparkfan 
 - [x] Add some extensions/skins used by default @Southparkfan 
 - [x] wgGroupPermissions for private/closed wikis @Southparkfan @NDKilla
- [x] Web server
 - [x] Add SSL cert stuff in Apache config & force HTTPS in VHosts @Southparkfan
 - [x] Add chained SSL cert in Apache & nginx config @Southparkfan @JohnFLewis 
 - [x] Create a secure ciphersuite with good compatibility @Southparkfan @JohnFLewis
 - [x] Write a php.ini for Apache (and set always_populate_raw_post_data=-1) @Southparkfan
- [x] Deployment
 - [x] Switch DNS to ns{12}.miraheze.org @JohnFLewis
 - [x] Verify uptake by root nameservers @JohnFLewis

**Comment by NDKilla** [comment]
Most group permissions should be done by pr #1
Pull request #4 enables read whitelist for logging into private wikis

**Comment by Reception123** [comment]
For the login this issue is that there are shared tables. Please read https://www.mediawiki.org/wiki/Extension:CentralAuth (Cache issues), and then it will explain how to get rid of the login issues. I'm not really sure about how to but I'm sure this is the error.

**Comment by Reception123** [comment]
Login issues fixed by Southparkfan.

**Comment by Reception123** [comment]
Extensions/Skins should be checked off.

**Comment by Southparkfan** [comment]
@Reception123 these are just very basic extensions/skins. A lot more should be added like: GlobalBlocking, CologneBlue, Modern, CategoryTree, Echo, Interwiki, Renameuser, Babel, CharInsert, InputBox, Poem, AntiSpoof, ApiSandbox, CodeEditor, Disambiguator, Gadgets, Thanks, etc.

**Comment by JohnFLewis** [comment]
This is done.
